'use client';
import { useEffect, useMemo, useState } from 'react'; import { useRouter } from 'next/navigation';
import { TEMPLATES, createWork, ensureMvpState, getWallet, markWorkCompleted, totalCredits, type Wallet } from '@/lib/mvpClientStore';
export default function CreatePage(){ const router=useRouter(); const [step,setStep]=useState(1); const [tpl,setTpl]=useState('tpl_001'); const [uploaded,setUploaded]=useState(false); const [fileName,setFileName]=useState(''); const [count,setCount]=useState<8|16|24>(8); const [wallet,setWallet]=useState<Wallet|null>(null); const [message,setMessage]=useState(''); const t=useMemo(()=>TEMPLATES.find(x=>x.id===tpl)||TEMPLATES[0],[tpl]); const cost=count;
 useEffect(()=>{ensureMvpState(); const initial=new URLSearchParams(window.location.search).get('template'); if(initial) setTpl(initial); setWallet(getWallet());},[]); const enough=wallet?totalCredits(wallet)>=cost:false;
 function onFile(e:React.ChangeEvent<HTMLInputElement>){ const f=e.target.files?.[0]; if(!f) return; if(!['image/jpeg','image/png','image/webp'].includes(f.type)){setMessage('僅支援 JPG、PNG、WebP'); return;} if(f.size>10*1024*1024){setMessage('單張照片最大 10MB'); return;} setUploaded(true); setFileName(f.name); setMessage('照片已通過格式檢查'); }
 function submit(){ setMessage(''); const r=createWork({templateId:tpl,count,title:`${t.name} ${count}張`}); if(!r.ok){ setWallet(getWallet()); setMessage(r.error); setStep(3); return; } setWallet(getWallet()); setStep(4); setMessage('已扣點並建立作品，mock 生成中…'); setTimeout(()=>{ markWorkCompleted(r.work.id); router.push(`/works/${r.work.id}`); },900); }
 return <main className="wide-page"><div className="page-header">建立貼圖</div><div className="step-guide commercial">{['上傳照片','選擇模板','確認張數與消耗點數','建立作品'].map((s,i)=><div key={s} className={`step-pill ${step>=i+1?'active':''}`}>{i+1}. {s}</div>)}</div>
 <section className="card desktop-card"><div className="credit-inline"><span>目前可用額度</span><b>{wallet?totalCredits(wallet):'--'} 點</b><small>免費 {wallet?.free_credits??0} / 贈送 {wallet?.bonus_credits??0} / 付費 {wallet?.paid_credits??0}</small></div></section>
 {step===1&&<section className="card desktop-card"><h2>Step 1：上傳照片</h2><p className="muted">建議使用正臉、光線清楚、五官完整的照片，生成效果會更好。</p><label className="upload-card input-upload"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={onFile}/><span className="upload-icon">📷</span><b>{uploaded?'已上傳：'+fileName:'選擇 JPG / PNG / WebP 照片'}</b><small>單張最大 10MB</small></label><button className="btn-primary" disabled={!uploaded} onClick={()=>setStep(2)}>下一步：選擇模板</button></section>}
 {step===2&&<section className="card desktop-card"><h2>Step 2：選擇模板</h2><div className="template-grid compact">{TEMPLATES.map(x=><button key={x.id} className={`template-card commercial ${tpl===x.id?'selected':''}`} onClick={()=>{setTpl(x.id); setCount(x.recommended_count)}}><div className="template-visual">{x.emoji}</div><div className="name">{x.name}</div><div className="desc">{x.description}</div><div className="tags">{x.credit_cost} 點</div></button>)}</div><div className="button-row"><button className="btn-secondary" onClick={()=>setStep(1)}>返回</button><button className="btn-primary" onClick={()=>setStep(3)}>下一步：確認點數</button></div></section>}
 {step===3&&<section className="card desktop-card"><h2>Step 3：確認張數與消耗點數</h2><div className="count-row">{([8,16,24] as const).map(n=><button key={n} className={`count-btn ${count===n?'active':''}`} onClick={()=>setCount(n)}>{n} 張<br/><small>{n} 點</small></button>)}</div><div className={`notice ${enough?'ok':'danger'}`}>{enough?`點數足夠，將依 免費點數 → 贈送點數 → 付費點數 扣除 ${cost} 點。`:'點數不足，請先購買額度後再建立作品。'}</div><div className="button-row"><button className="btn-secondary" onClick={()=>setStep(2)}>返回</button>{enough?<button className="btn-primary" onClick={submit}>Step 4：建立作品</button>:<button className="btn-primary" onClick={()=>router.push('/billing')}>前往購買點數</button>}</div></section>}
 {step===4&&<section className="card desktop-card"><h2>Step 4：建立作品</h2><p>{message}</p><div className="skeleton" style={{height:18, marginTop:16}} /></section>}
 {message&&step!==4&&<div className="notice danger">{message}</div>}
 </main> }
